build: get rid of failing snapcore/action-build@v1 action

diff --git a/.github/workflows/glpi-agent-packaging.yml b/.github/workflows/glpi-agent-packaging.yml
--- a/.github/workflows/glpi-agent-packaging.yml
+++ b/.github/workflows/glpi-agent-packaging.yml
@@ -286,10 +286,30 @@ jobs:
 
     steps:
     - uses: actions/checkout@v2
-    - uses: snapcore/action-build@v1
+    - name: Install snapcraft
+      # Emulate what is really done by snapcore/action-build@v1 action but without failure on snap refresh lxd
+      run: |
+        echo "Ensuring runner is in the lxd group..."
+        sudo groupadd --force --system lxd
+        sudo usermod --append --groups lxd runner
+        if snap refresh --list | egrep -q "^lxd"; then
+            echo "Refreshing lxd snap"
+            sudo snap refresh lxd || true
+        fi
+        echo "Initialising LXD..."
+        sudo lxd init --auto
+        echo "Installing Snapcraft..."
+        sudo snap install --channel stable --classic snapcraft
+      shell: bash
+    - name: Build snap with snapcraft
       id: snapcraft
       env:
         TERM: ${{ env.TERM }}:${{ needs.setup-release.outputs.version }}
+        SNAPCRAFT_BUILD_ENVIRONMENT: lxd
+      run: |
+        sg lxd -c snapcraft
+        echo "::set-output name=snap::$(ls *.snap 2>/dev/null)"
+      shell: bash
     - name: Upload Snap built artifacts
       uses: actions/upload-artifact@v2
       with:
